//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeworkW5D2_New
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlbumHomeworkDBEntities : DbContext
    {
        public AlbumHomeworkDBEntities()
            : base("name=AlbumHomeworkDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlbumTable> AlbumTables { get; set; }
        public virtual DbSet<ArtistTable> ArtistTables { get; set; }
        public virtual DbSet<GenreTable> GenreTables { get; set; }
    }
}
