//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeworkW5D2_New
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlbumTable
    {
        public int AlbumID { get; set; }
        public string AlbumName { get; set; }
        public int ArtistID { get; set; }
        public int GenreID { get; set; }
        public byte[] Image { get; set; }
    
        public virtual ArtistTable ArtistTable { get; set; }
        public virtual GenreTable GenreTable { get; set; }
    }
}
